name = "giga-shipment-sync-worker-production"
main = "src/worker.js"
compatibility_date = "2026-02-11"

[vars]
GIGA_CLIENT_ID = "83142311_JPN_release"
GIGA_API_BASE_URL = "https://openapi.gigab2b.com"
YOUGE_APP_CODE = "apbhhitm6xica7akck"
YOUGE_SCHEMA_CODE = "smhdzccpti8vrlyzj0"
YOUGE_ENGINE_CODE = "c00000000000s4-0"
YOUGE_BASE_URL = "https://sanyu.cloud"

[env.dev]
name = "giga-shipment-sync-worker-dev"
[env.dev.vars]
GIGA_CLIENT_ID = "83142311_JPN_release"
GIGA_API_BASE_URL = "https://openapi-sandbox.gigab2b.com"
YOUGE_APP_CODE = "apbhhitm6xica7akck"
YOUGE_SCHEMA_CODE = "smhdzccpti8vrlyzj0"
YOUGE_ENGINE_CODE = "c00000000000s4-0"
YOUGE_BASE_URL = "https://sanyu.cloud"

[env.production]
name = "giga-shipment-sync-worker"
[env.production.vars]
GIGA_CLIENT_ID = "83142311_JPN_release"
GIGA_API_BASE_URL = "https://openapi.gigab2b.com"
YOUGE_APP_CODE = "apbhhitm6xica7akck"
YOUGE_SCHEMA_CODE = "smhdzccpti8vrlyzj0"
YOUGE_ENGINE_CODE = "c00000000000s4-0"
YOUGE_BASE_URL = "https://sanyu.cloud"

[env.production.triggers]
crons = ["0 2,5,9 * * *"]

# Note: GIGA_CLIENT_SECRET and YOUGE_APP_TOKEN must be set via `wrangler secret put` for each environment
